name: easpos
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  shimmer: ^2.0.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  rxdart: ^0.27.1
  flutter_bloc: ^6.1.1
  flutter_rating_bar: ^4.0.0
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.4
  flutter_spinkit: ^5.0.0
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.3
  firebase_messaging: ^10.0.0
  cached_network_image: ^3.0.0
  bubble: ^1.2.1
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.0.7
  flutter_staggered_grid_view: ^0.4.0
  awesome_dialog: ^2.1.0
  connectivity: ^3.0.6
  app_settings: ^4.1.0
  image_picker: ^0.7.5+3
  flutter_image_compress: ^1.0.0
  image_cropper: ^1.4.0
  firebase_dynamic_links: ^2.0.4
  font_awesome_flutter: ^9.0.0
  pin_code_fields: ^7.2.0
  country_code_picker: ^2.0.1
  google_sign_in: ^5.0.4
  # ----------------------------- FireBase
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  the_apple_sign_in: ^1.1.1
  #  flutter_facebook_login: ^3.0.0
  multi_image_picker2: ^5.0.0
  intl: ^0.17.0
  scroll_to_index: ^2.0.0
  geocoder: ^0.2.1
  google_maps_flutter: 2.0.6
  geolocator: ^7.0.3

  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600

